apiVersion: v1
kind: Service
metadata:
  name: php-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
spec:
  selector:
    app: php-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
